---
# Setup of the CernVM-File system (CVMFS) and configure so that the reference
# data hosted by Galaxy on usegalaxy.org is available to the remote target.

# Install autofs
- name: Install autofs system package
  apt:
    name: ['autofs', 'uuid-runtime']
    state: "{{ galaxy_extras_apt_package_state }}"
  when: galaxy_extras_install_packages

- name: Install CernVM apt key
  apt_key:
    url: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg

# Install & setup CermVM-FS
- name: Configure CernVM apt repository
  apt_repository:
    filename: "cernvm.list"
    mode: 422
    repo: deb https://cvmrepo.web.cern.ch/cvmrepo/apt/ {{ ansible_distribution_release }}-prod main

- name: Install CernVM-FS client (apt)
  apt:
    name: ['cvmfs', 'cvmfs-config']
    state: "{{ galaxy_extras_apt_package_state }}"
    update_cache: yes

- name: Install CernVM-FS keys
  copy:
    content: "{{ item.key }}"
    dest: "{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "0444"
  with_items: "{{ cvmfs_keys }}"

- name: Perform AutoFS and FUSE configuration for CernVM-FS
  command: cvmfs_config setup

- name: Configure CernVM-FS domain
  copy:
    content: |
      CVMFS_SERVER_URL="{{ item.urls | join(';') }}"
    dest: "/etc/cvmfs/domain.d/{{ item.domain }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ cvmfs_server_urls }}"

- name: Configure CernVM-FS client settings
  copy:
    content: |
      CVMFS_REPOSITORIES="{%- for repo in cvmfs_repositories -%}{{ ',' if loop.index0 > 0 else '' }}{{ repo.repository }}{%- endfor -%}"
      CVMFS_HTTP_PROXY="{{ cvmfs_http_proxies | join(';') }}"
      CVMFS_QUOTA_LIMIT="{{ cvmfs_quota_limit | default('4000') }}"
      CVMFS_USE_GEOAPI="{{ cvmfs_use_geoapi | default('yes') }}"
    dest: "/etc/cvmfs/default.local"
    owner: "root"
    group: "root"
    mode: "0644"

# Create a symlink from the CVMFS to /galaxy/data because that is where the
# .loc files from CVMFS point (and consequently tool_data_table_conf.xml)
- name: Create /galaxy dir
  file: path=/galaxy state=directory

# This is required to be able to use Galaxy .len files from Main w/o mods
- name: Create a symlink from CVMFS to /galaxy/data
  file: src=/cvmfs/data.galaxyproject.org/byhand dest=/galaxy/data state=link force=yes

- name: Use tool_data_table_conf.xml from usegalaxy-playbook
  get_url:
    url: https://raw.githubusercontent.com/galaxyproject/usegalaxy-playbook/067433f547f67b848f2e4597274a379f06da04b2/files/galaxy/usegalaxy.org/config/tool_data_table_conf.xml
    dest: "{{ galaxy_tool_data_table_config_file }}"

# The following two tasks need to be at the bottom of this file
- name: Stop autofs service
  service:
    name: autofs
    state: stopped

- name: Remove autofs service file since we're using Supervisor
  file:
    path: /etc/init/autofs.conf
    state: absent
