---

- name: Check if the Ubuntu distro is supported
  get_url: url="https://deb.nodesource.com/node_10.x/dists/{{ ansible_distribution_release }}/Release" dest=/dev/null
  register: distro_supported
  when: galaxy_minimum_version < "19.01"

- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state={{ galaxy_extras_apt_package_state }}
  when: distro_supported is succeeded and galaxy_minimum_version < "19.01"

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: "{{ galaxy_extras_apt_package_state }}"
  when: distro_supported is succeeded and galaxy_minimum_version < "19.01"

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: "{{ galaxy_extras_apt_package_state }}"
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  when: distro_supported is succeeded and galaxy_minimum_version < "19.01"

- name: Install nodejs (npm is included)
  apt: pkg=nodejs state=latest update_cache=true
  when: galaxy_minimum_version < "19.01"

- name: "Install proxy dependencies (>=19.01)."
  shell: ". {{ galaxy_venv_dir }}/bin/activate && npm config set strict-ssl false && npm install && deactivate"
  args:
    chdir: "{{ galaxy_server_dir }}/lib/galaxy/web/proxy/js"
  become: True
  become_user: "{{ galaxy_user_name }}"
  when: galaxy_minimum_version >= "19.01"

- name: "Install proxy dependencies (<19.01)."
  shell: "cd {{ galaxy_server_dir }}/lib/galaxy/web/proxy/js && npm config set strict-ssl false && npm install"
  become: True
  become_user: "{{ galaxy_user_name }}"
  when: galaxy_minimum_version < "19.01"

- name: "Install Juypter container."
  shell: "docker pull {{ galaxy_extras_ie_jupyter_image }}"
  become: True
  when: galaxy_extras_ie_fetch_jupyter

- name: "Install RStudio container."
  shell: "docker pull {{ galaxy_extras_ie_rstudio_image }}"
  become: True
  when: galaxy_extras_ie_fetch_rstudio
