
- include: galaxy_root.yml
  when: galaxy_extras_config_galaxy_root

- include: galaxy_metrics.yml
  when: galaxy_extras_config_galaxy_root

- include: uwsgi.yml
  when: galaxy_extras_config_uwsgi

- include: nginx.yml
  when: galaxy_extras_config_nginx
  tags:
   - nginx_config
   - nginx

- include: proftpd.yml
  when: galaxy_extras_config_proftpd
  tags:
   - proftpd

- include: slurm.yml
  when: galaxy_extras_config_slurm
  tags:
   - slurm

- include: pbs.yml
  when: galaxy_extras_config_pbs

- include: supervisor.yml
  when: galaxy_extras_config_supervisor

- include: ie_proxy.yml
  when: galaxy_extras_config_ie_proxy

- include: galaxy_scripts.yml
  when: galaxy_extras_config_scripts

- include: rabbitmq.yml
  when: galaxy_extras_config_rabbitmq

- include: startup.yml
  when: galaxy_extras_config_startup
