- name: Install PBS/torque system packages
  apt: 
    state: "{{ galaxy_extras_apt_package_state }}"
    name: "{{ packages }}"
  vars:
    packages:
    - torque-client
    - pbs-drmaa-dev
  when: galaxy_extras_install_packages

# If job_conf.xml is installed before running galaxyprojectdotorg.galaxy, this would already be installed.
- name: Fetch DRMAA wheel for Galaxy
  pip:
    name: "drmaa"
    extra_args: "--index-url https://wheels.galaxyproject.org/simple/ --extra-index-url https://pypi.python.org/simple"
    virtualenv: "{{ galaxy_venv_dir }}"
  environment:
    PYTHOPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"

- name: "Install Galaxy job conf"
  template: src=job_conf.xml.j2 dest={{galaxy_job_conf_path}} owner={{ galaxy_user_name }} group={{ galaxy_user_name }}
  tags: galaxy_extras_job_conf

- name: "Set PBS/torque server name"
  lineinfile: dest=/etc/torque/server_name line={{ pbs_server_name }} state=present create=yes
