# Attempt to restart nginx (if nginx is running)
#- name: nginx status
#  stat: path=/run/nginx.pid
#  register: nginx_status

#- name: Restart Nginx
#  command: /usr/sbin/nginx -s reload
#  become: yes
#  become_user: root
#  when: nginx_status.stat.islnk is defined
